apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mvasilenko-blog
spec:
  terminationGracePeriodSeconds: 30
  replicas: 2 
  template:
    metadata:
      labels:
        app: mvasilenko-blog
    spec:
      containers:
        - name: mvasilenko-blog
          image: mvasilenko/mvasilenko-blog:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
